@GameStore_HostAddress = http://localhost:5180

// TOKEN =============================================
GET {{GameStore_HostAddress}}/weatherforecast/
Accept: application/json

// GAMES =============================================
###
GET {{GameStore_HostAddress}}/games

###
GET {{GameStore_HostAddress}}/games/3

###
POST {{GameStore_HostAddress}}/games
Content-Type: application/json

{
    "name": "TEST GAME 2",
    "genreId": 2,
    "price": 49.99,
    "releaseDate": "2024-11-23"
}
###
PUT {{GameStore_HostAddress}}/games/1
Content-Type: application/json

{
    "name": "Street fIghter II",
    "genreId": 2,
    "price": 48.99,
    "releaseDate": "1992-07-15"
}

###
DELETE {{GameStore_HostAddress}}/games/3

// GENRES ==========================================
###
GET {{GameStore_HostAddress}}/genres

// USERS ===========================================
###
POST {{GameStore_HostAddress}}/api/register
Content-Type: application/json

{
    "email": "qwe@qw.com",
    "password": "zxcvb89"
}

